apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  labels:
    app: kafka-consumer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: docker.io/bitnami/kafka:3.3.1-debian-11-r25
        command:
        - "/bin/bash"
        - "-c"
        - "kafka-console-consumer.sh --group demo --topic demo --from-beginning --bootstrap-server demo-kafka:9092"