apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: test
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    listenAddress: "0.0.0.0"
    protocol: tcp