apiVersion: v2
name: demo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: keda
    repository: https://kedacore.github.io/charts
    version: '2.9.1'
  - name: kafka
    repository: 'https://charts.bitnami.com/bitnami'
    version: '20.0.2'