kafka:
  persistence:
    enabled: false
  externalAccess:
    enabled: true
    service:
      type: NodePort
      nodePorts:
        - 30001
  provisioning:
    enabled: true
    topics:
    - name: demo
      partitions: 1
      replicationFactor: 1
      ## https://kafka.apache.org/documentation/#topicconfigs
      # config:
      #   max.message.bytes: 64000
      #   flush.messages: 1